### ISSUE TITLE
How to answer question?

### ISSUE THREAD

**Issue by GideonWolfe** [sharktamer/sopel-quiz#1]
I tried to look through the code but it really isn't obvious nor is there any info in the readme.

I easily can start a quiz with `.quiz` but then it just times out saying nobody answered no matter what I type? What is the format to submit an answer to the quiz?

**Comment by surskitt** [comment]
You're supposed to just be able to answer the question in chat, no prefix or format needed.

**Comment by surskitt** [comment]
I'll be honest, I'm surprised anyone is even using this. I've had unpushed code sitting on my PC for months now that I've just pushed. There's also a pip module found here:

https://pypi.org/project/sopel-modules.quiz

You can just pip install to get the module, that may work a little better for you although I don't think the actual code is any different.

**Comment by GideonWolfe** [comment]
I did actually install through pip, I just got linked back here to make the issue. I might have to change the category for me and my friends, cuz we can't get them and no matter what we say in the chat we get "No answer within 30 seconds".

So i'm not sure if it's picky or we're just stupid.

EDIT: It's the latter. Got one right and it works fine!
